# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis python-coveralls

# command to run tests, e.g. python setup.py test
script: tox

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup

#branches:
#  only:
#  - master
#  - develop

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: vilkas
  password:
    secure: iVR7HfSjApCelmobwSQQDiltY1Z2HSg50d21GWsoFkWMUAmp6/0w2ES8dumxCggs4T0hQMy/i7wJ9DnXL4ZiOG20PcXtNEPKdpBziUK6cByO7k5dzWTvRJYi4YTOHIj/rhutEZaKdaUyhb2GYORc9AyYOzZHBamELa0LxDsIt6pfuOudu6HPcXC8MlRlXnkuJz0Gx/hm8rno38wQbCImpQA4ial440n1GvaYkUKea3v0VAGB68W1bw4B8ZDLkXPqi8CKk7qNMVyeiLQZtdRmnyktHH3S9CkqYQ9zvlyNlxJliupe/eJ1FQuYj8SYJh9CmpQ4k+1JehP0eSizjiXt+TiYEKpiOF1xmZepFjrv/FXe6z882b8rQCUv4Z054i2X09OLDccrDESG9SQ50XfoPD/yibLehw+Axq/hNKeafyy0fjcfRJZSp8yKTwRnHtwMP2kMnITCCe+Ox7aV6Ib+YCwFlba0JTGyoS/Bz4Dgw3cixOvCtNLssFI2g6lKwFAu8JvrZeHQ1QfDTOUCLUwkoQ+pPPxAWpV70ds/vs71fD9mYwo1Sy/TPuelKkZMQXhxglJA77ZITsQhvBB/YdKGqx+fRHtVXPefYJJGfWeXeTbeVWO46Gy0cE3Dg7ubipMUo5dblDyTc/zC9/eluu9xcr02xZ9kWI3bbfxme2wbfbs=
  true:
    python: 2.7
    repo: vilkasgroup/Procountor
    tags: true
    all_branches: true

after_success:
  - coverage run --source procountor setup.py test
  - coverage report
  - coveralls
